### ISSUE TITLE
JsonKnownTypesException: "Type has no constructor without parameters"

### ISSUE THREAD

**Issue by bddckr** [dmitry-bym/JsonKnownTypes#10]
The latest version of this library switched from previously leaving deserialization completely up to JSON.NET to instead create an instance manually and then `Populate` it via JSON.NET: https://github.com/dmitry-bym/JsonKnownTypes/commit/36d165a794aabf0befc9e8f33e9149b80557c4ef#diff-9c5f01bda10146eed49209469f849a72R31-R38

This approach has a drawback that introduces a breaking change in comparison with the previous versions of the library: JSON.NET is able to use constructors that specify parameters, as long as they match the JSON properties. The new library approach to create instances manually relies on finding a parameter-less constructor.
(There's the ability to mark a constructor specifically with `[JsonConstructor]` in case there are multiple ones. This attribute thus allows to override the default behavior of always choosing the parameter-less constructor in case there are multiple of them.)

As I think it might become a little too complex to create and maintain the same logic basically, I'm wondering whether JsonKnownTypes can go back to the previous behavior for this, while also keeping the new performance optimizations introduced by the linked change.

**Comment by dmitry-bym** [comment]
Hello, Yeap, i see the problem, and i resolve it, but i needed some time for testing, i don't think that somebody actualy have the problem, i build new version for a day

**Comment by bddckr** [comment]
Thank you Dmitry!

In general the commit I linked did something wonderful: The `JsonSerializer` that is passed into the `ReadJson` and `WriteJson` methods is used now. That in turn allows me to resolve an issue I have where I have to specify my own settings (for a few types at least).

I'm hitting this issue because I'm updating to the latest NuGet version thanks to your changes for #6.

No rush and thanks for looking into this!

**Comment by dmitry-bym** [comment]
Ok, i created new version and its already published on nuget, thanks for reminding, i just forgot to release), now it is working like in write json with threadLocal var
https://github.com/dmitry-bym/JsonKnownTypes/blob/73ffa796677f38f1c3c6ade1342381699fad567c/src/JsonKnownTypes/JsonKnownTypesConverter.cs#L24-L49

**Comment by bddckr** [comment]
I can confirm this works! I tested both serializing and deserializing my specific types and had no issues.

Thanks for the awesome library and the fast work! ❤️
