### ISSUE TITLE
Derived type is in another assembly

### ISSUE THREAD

**Issue by theglobe** [dmitry-bym/JsonKnownTypes#13]
In this example:
```
[JsonConverter(typeof(JsonKnownTypesConverter<IInterface>))]
[JsonKnownType(typeof(ChildClass))]
public interface IInterface  { ... }
public class ChildClass : IInterface  { ... }
```
What if ChildClass (and there are several heirs) is in another assembly, and it is not possible to reference that assembly because of circular reference?

**Comment by bddckr** [comment]
See #6 😃

**Comment by theglobe** [comment]
Thanks! :D

**Comment by theglobe** [comment]
Would be good to write this example in the Documentation, since it is quite a common use case.

**Comment by dmitry-bym** [comment]
@bddckr hi, I had no time to answer, thanx for help). @theglobe Hi, i try to write doc as soon as i can

**Comment by dmitry-bym** [comment]
Added to readme
