### ISSUE TITLE
Warning CS8002: Referenced assembly 'JsonKnownTypes, Version=0.4.1.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

### ISSUE THREAD

**Issue by swtrse** [dmitry-bym/JsonKnownTypes#15]
Please provide your package with strong named assemblies.

Thanks

**Comment by dmitry-bym** [comment]
Hello, thanx for issue. Sorry, i will not provide strong name. Because it means i'll need to support two packages. If you need that you can download it and build yourself
