### ISSUE TITLE
Any issues with the PreserveReferencesHandling

### ISSUE THREAD

**Issue by savasozer** [dmitry-bym/JsonKnownTypes#33]
Hi all,
Is there any known issues with the PreserveReferencesHandling option. I'm asking this because I'm getting an exception as following. I couldn't send any code here to reproduce the issue because of my project size.

BTW: I'm sure my all classes have JsonKnownThisType attribute.

![image](https://github.com/dmitry-bym/JsonKnownTypes/assets/12625556/a5803511-7379-4601-a26f-0bfe8b3c5d29)

Thank you.

**Comment by dmitry-bym** [comment]
need code example
