### ISSUE TITLE
Inheritance lookup restricts to same assembly

### ISSUE THREAD

**Issue by bddckr** [dmitry-bym/JsonKnownTypes#6]
Thanks a lot for this library! It took me a while to have a use for _both_ `JsonKnownType` and `JsonKnownThisType`, but now I have a really great setup for persisting discriminated unions (generated by [`language-ext`](https://github.com/louthy/language-ext/wiki/Code-generation#discriminated-union--sum-types)) ❤️

---

I have an interface I define in project A.

In project B I have a reference to project A. In this project B I add types that implement the interface of A.

Currently those types in B won't be found by this library, due to this:
https://github.com/dmitry-bym/JsonKnownTypes/blob/60efa0da093ee713f425a6a751a27fe15e71a1dc/src/JsonKnownTypes/JsonKnownTypesSettingsManager.cs#L46-L53

I've successfully used [`AppDomain.GetAssemblies`](https://docs.microsoft.com/dotnet/api/system.appdomain.getassemblies?view=netstandard-2.0) to do the above on all of those assemblies, however that is probably not a solution that works for everyone: Not all assemblies with the needed types might be loaded yet when this runs, but we also don't want to look up all assemblies and trigger a load either...

So while that suggested change works for me currently, I'm wondering if there is a better way to do this. Also, I'd love for this change (or a better one) to be merged into this library, so I can get rid of my private fork, but I understand that the above concerns might be resulting in such a change not being incorporated.

**Comment by dmitry-bym** [comment]
Hi @bddckr, thanx for your review), i see your problem, i add some solution to next version, i think it will be some virtual method, i don't know exactly.

**Comment by bddckr** [comment]
That's actually a very reasonable approach. A colleague suggested opening up this type registration via some accessible API, but we are aware that's kind of a bigger change.

Thanks for looking into this whenever you get some time for it!

**Comment by dmitry-bym** [comment]
@bddckr Hi, i added func and you can initialize it yourself as you need. I think i will released it in a week. 
https://github.com/dmitry-bym/JsonKnownTypes/blob/2aa0f2380b796944438401238f3f857422616de6/src/JsonKnownTypes/JsonKnownTypesSettingsManager.cs#L16-L20

**Comment by bddckr** [comment]
That is perfect!

No worries on the timeline. Seeing that this should work for my team just fine I'll wait for a NuGet release before I remove our workaround.

Thanks again for your work!

**Comment by dmitry-bym** [comment]
Hi, @bddckr, I uploaded new version to nuget
